### ISSUE TITLE
[BUG] Built-in :clang and :gcc toolchains fail to link on MacOS

### ISSUE THREAD

**Issue by tcbrindle** [vector-of-bool/dds#25]
**Describe the bug**

The built-in `:clang` toolchain uses the `-static-libgcc -static-libstdc++` link options, neither of which are supported on MacOS. The same thing happens with `:gcc`, as `g++` is an alias for `clang++` on the Mac.

**Steps to Reproduce**

1. Follow the first steps from the [DDS tutorial](https://vector-of-bool.github.io/docs/dds/tut/hello-world.html)
2. Attempt to build with `dds build -t :clang` as instructed
3. Observe linker error

**`dds` Output**

```
[14:04:17] [error] Failed to link executable [/path/to/example/_build/hello-world]. Link command was [clang++ -fPIC /path/to/example/_build/obj/hello-world.main.cpp.o -pthread -o/path/to/_build/hello-world -static-libgcc -static-libstdc++] [Exited 1], produced output:
clang: error: unsupported option '-static-libgcc'

[14:04:17] [error] Linking a runtime binary (executable/shared library/DLL) failed
[14:04:17] [error] 
Linking a runtime binary file failed. There are a variety of possible causes
for this error. Refer to the documentation for more information.

[14:04:17] [error] Refer: https://vector-of-bool.github.io/docs/dds/err/link-failure.html
```

**Desktop (please complete the following information):**

 - Operating System: macOS
 - Compiler: Clang
 - `dds` Version: 0.1.0-alpha.3

**Comment by vector-of-bool** [comment]
Dang. I thought I'd had this one covered. I need to add Clang to the test suite.

I'm not sure how to best handle `gcc` being an alias for `clang`. It's such a massive hack that just happens to work for many cases, but I'd seriously prefer if they didn't ship it like that. I may have to make static-runtime an opt-in instead of implicit, i.e. `:static:gcc`.

The upcoming release I want to add toolchain knobs that control the runtime selection. i.e. static/dynamic & debug/release, especially since these are essential features on MSVC with `/MT` and friends.

**Comment by tcbrindle** [comment]
Yeah, I don't think it's a big deal if `:gcc` doesn't work out of the box on the Mac, given that it's pretty much just a hack to keep Makefiles from a bygone era working, but I thought I'd mention it for completeness.
