### ISSUE TITLE
[BUG] Crash when a malformed sdist directory appears in the local repository (Should warn instead).

### ISSUE THREAD

**Issue by luketrevorrow** [vector-of-bool/dds#35]
When I try and follow the tutorial for setting up dds for the first time, under MSVC Developer Command Prompt and Powershell I get the following error:

```
PS C:\Users\luket\src\shopping-guru> dds build -t :msvc

      HALT: CONTRACT VIOLATION
      ----- ------------------
      What: A class/library/function invariant was broken.
  Expected: pkg_man.has_value()
  Location: File "D:\a\1\s\src\dds\source\dist.cpp", line 129,
            in [struct dds::sdist __cdecl dds::sdist::from_directory(const class std::filesystem::path &)]
   Message: All dirs in the repo should be proper source distributions. If you see this, it means one of the directories in the repository is not a valid sdist.
   Context: where.string() := C:\Users\luket\AppData\Local\dds\repo\example-strings@1.0.0
```

If I run the same command under WSL using the Linux version of DDS everything works hunky dory! My file location is not as described in the error message but as shown under the PS command prompt above. ( C:\Users\luket\src\shopping-guru\src\hello-world.main.cpp)

**Comment by luketrevorrow** [comment]
Just as an aside - it seems to work with DDS alpha 3, btw

**Comment by vector-of-bool** [comment]
This one is a known goof. It *should actually* be an error message instead of a hard-assert. Basically, with a newer alpha I modified the format of sdists in the local repository, and I have an assert that every sdist in the local repo is well-formed. In this case, the sdist directory at `C:\Users\luket\AppData\Local\dds\repo\example-strings@1.0.0` is bad, probably because it was exported by a prior release that used the old format. If you delete that directory and try again, it should go smoothly.

I'll open a new ticket to convert the assert into a proper warning message.
