### ISSUE TITLE
[FEATURE] OS-Specific compilation based on filename

### ISSUE THREAD

**Issue by Algo-ryth-mix** [vector-of-bool/dds#55]
**Describe the scenario and circumstances that should be addressed**

Many Libraries have different headers and source files based on what operating system they run on (for instance GLFW). For some of those it is not trivial to simply replace them with calls from the stl. Simply disabling the files that are not intended for the current os has the potential to make the libraries compatible or trivial to port to dds.

**Describe alternatives you've considered**

Alternatives would be configuration steps like CMake has, but I think that works against the simple nature of dds

**Describe the solution you'd like**

Files that end (or possibly start) with an identifier for that operating system should only be considered part of the build if it matches the operating system it is built on.
For instance:

` input.win.cpp ` 
` window.linux.cpp `

(alternatively `win_input.cpp` or `linux_window.cpp` or something similiar)

**Comment by vector-of-bool** [comment]
Thanks for the request!

This was actually the route I was initially approaching with `dds`, but decided against it for one reason: It is, in general, _not possible_ to reliably know ahead-of-time what files _should_ or _should not_ be included in compilation, because that may vary arbitrarily based on the toolchain used in the build. For example: If we are compiling on Linux with MinGW, then we _might_ want to compile the Windows version of the sources and omit the \*nix versions. If we are targeting WebAssembly, we'll need to do something completely different. `dds` has no attributes in the toolchain that inform it enough to make these decisions on its own. 

The route I went with instead is to rely on the preprocessor to perform conditional compilation based on built-in per-system macro definitions. These are able to handle arbitrary complex use cases and conditions, and can even be controlled via tweak-headers and toolchain preprocessor definitions.

Using fully-conditional files is how `dds` does this itself, consider: [proc.win.cpp](https://github.com/vector-of-bool/dds/blob/develop/src/dds/proc.win.cpp) versus [proc.nix.cpp](https://github.com/vector-of-bool/dds/blob/develop/src/dds/proc.nix.cpp), which both implement the same API but are conditionally enabled on the system's preprocessor state.

---

**As for importing external libraries:** While I would love it if all libraries adopt the above method instead of relying on configure-time scripting, I don't expect everyone to hop on the bandwagon immediately just to placate `dds`.

`dds` uses source-distributions as its packaging format, and this is just a bundle of source files that `dds` will compile into a library. The contents of the source-distribution need not be identical to the content of the origin source repository. Several of the packages available in the `repo-1.dds.pizza` repository are actually created by first cloning _then transforming_ the original repository, including patching files and rearranging the file tree. The script that automatically generates these "`dds` ports" is not (yet) publicly available, but isn't anything particularly interesting.

The final test on the viability of this design is to generate a working `dds`-buildable port of `ImGui`.

While it _is_ more work than just throwing files at `dds` to compile, it is not something blocking, and I don't (yet) have a sufficient motivation to change it. I'll close this ticket for now, but may revisit it in the future if there is a compelling use case that isn't otherwise covered above.

Thank you again for your interest!

**Comment by Algo-ryth-mix** [comment]
Ah I see. So in that case I'll just have to adapt the files for GLFW slightly and "guard" them behind the os specific defines. Is there a way in `dds` to add additional defines, (for things like X11 vs Wayland) or would that be step that an alternate tool would need to take first ?

**Comment by vector-of-bool** [comment]
It depends on what you need those definitions to do. There is the overly-powerful option to just provide `-DSOME_DEFINITION` at the toolchain level, but `dds` supports and prefers the usage of tweak-headers with the `--tweaks-dir` argument to `build`. ([Refer to this article](https://vector-of-bool.github.io/2020/10/04/lib-configuration.html).) Patching an existing library to support a tweak-header is often very simple.

For reference, look at the SQLite3 package:

```sh
dds pkg get sqlite3@3.34.0
```

The change to support a tweak-header in SQLite is just at the top of the file at `src/sqlite3/sqlite3.h`. For an example that customizes SQLite in this way, look into the `conf/` directory and `azure-pipelines.yml` file for [neo-sqlite3](https://github.com/vector-of-bool/neo-sqlite3).
